import { Inter } from "next/font/google"
import "./globals.css";
import dbConnect from "@/service/dbConnect";
import Navbar from "./components/Navbar";
import SessionWrapper from "./components/SessionWrapper";
const inter = Inter({ subsets: ["latin"] })



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    await dbConnect()
   
  return (
    <html
      lang="en"
      className={ inter.className}
    >
      <body className="min-h-full flex flex-col">
        
        <SessionWrapper>
          <Navbar/> {children}</SessionWrapper>
       </body>
    </html>
  );
}
